// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AddTxtFileVSIX
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidAddTxtFileVSIXPackageString = "17a0f54e-ccc0-46cf-832e-d0c683ce1282";
        public static Guid guidAddTxtFileVSIXPackage = new Guid(guidAddTxtFileVSIXPackageString);

        public const string guidAddTxtFileVSIXPackageCmdSetString = "23fd2bb8-19ac-4280-bb93-71a9e62a4052";
        public static Guid guidAddTxtFileVSIXPackageCmdSet = new Guid(guidAddTxtFileVSIXPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int AddItemToolWindowCommandId = 0x0100;
    }
}